import 'package:flutter/material.dart';
import 'package:my_first/navigation.dart';

class Gre extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
            drawer:MenuDashboard(),
            backgroundColor: Color(0xffF1FAEE),
            appBar: AppBar(
              backgroundColor: Color(0xff457B9D),
              title: Text('Exam'),
            ),
            body: ListView(
              children: <Widget>[
                titleSection,
              ],
            ),
    );
  }

  Widget titleSection= Container(
      child:Column(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: <Widget>[
          Padding(
            padding:const EdgeInsets.all(8.0),
            child:Text(
              "GRE",
              style:TextStyle(
                fontWeight:FontWeight.bold,
                fontSize:35,
                color:Color(0xff1D3557),
              ),

            ),
          ),
          Padding(
            padding:const EdgeInsets.all(8.0),
            child:Text(
              '''The Graduate Record Examination, or GRE, is an important step in the graduate school or business school application process. The GRE is a multiple-choice, computer-based, standardized exam that is often required for admission to graduate programs and graduate business programs (MBA) globally.

The GRE is developed and administered by testmaker ETS to provide graduate and business schools with common measures for comparing applicants’ qualifications and preparedness for graduate-level academic work. Graduate school and business school admissions committees look at your GRE score, along with your academic record and supporting materials, to assess your readiness for the rigors of graduate academic study.
You will receive three scores on the GRE:
Analytical Writing
Verbal Reasoning
Quantitative Reasoning
 These scores are generated by the following sections:

1 Analytical Writing Assessment section
2 Verbal Reasoning sections
2 Quantitative Reasoning sections
In addition, you will see one of the following sections:

Unscored (may be either Verbal Reasoning or Quantitative Reasoning)
Research (used for ETS research purposes)
The Quantitative Reasoning and Verbal Reasoning sections are each scored on a scale of 130 to 170. The mean score for Verbal Reasoning is 151, and the mean score for Quantitative Reasoning is 153. The Analytical Writing Assessment is scored from 0 to 6 in half-point increments, and the mean score is 4.0''',
                  style:TextStyle(
                  fontWeight:FontWeight.bold,
                  fontSize:20.0,
                  color:Colors.black
              ),

            ),
          ),
        ],
      )
  );
}